# Generated by Django 4.1.5 on 2023-01-31 04:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Past',
            new_name='Post',
        ),
    ]
