# Generated by Django 4.1.5 on 2023-02-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_rename_past_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='dp/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
